# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY init_db.py /app/init_db.py

# Install any needed packages specified in requirements.txt
RUN pip install asyncpg

# Run init_db.py when the container launches
CMD ["python", "/app/init_db.py"]
